version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5437:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
